#!/usr/bin/env bash
# Forge Flow pre-push hook — runs /preflight-ci if any locked in-progress task
# on this machine has preflight_required: true.
#
# Generated by `forge preflight enable-git-hook`. Remove with
# `forge preflight disable-git-hook` — do not edit directly.
#
# Sentinel: FORGE_PREFLIGHT_HOOK_V1

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${REPO_ROOT}" ]]; then
  exit 0  # Not a git repo — nothing to do
fi

FORGE_PY="${REPO_ROOT}/.claude/scripts/forge/forge.py"
PREFLIGHT_PY="${REPO_ROOT}/.claude/scripts/preflight/preflight.py"

# Both layouts: framework dev (scripts/forge) and consumer (.claude/scripts/forge)
if [[ ! -f "${FORGE_PY}" ]]; then
  FORGE_PY="${REPO_ROOT}/scripts/forge/forge.py"
fi
if [[ ! -f "${PREFLIGHT_PY}" ]]; then
  PREFLIGHT_PY="${REPO_ROOT}/scripts/preflight/preflight.py"
fi

if [[ ! -f "${FORGE_PY}" || ! -f "${PREFLIGHT_PY}" ]]; then
  echo "preflight: forge or preflight script missing — skipping" >&2
  exit 0
fi

# Allow explicit bypass (rare).
if [[ "${FORGE_SKIP_PREFLIGHT:-}" == "1" ]]; then
  echo "preflight: FORGE_SKIP_PREFLIGHT=1 — skipping" >&2
  exit 0
fi

# Resolve PYTHON_BIN: prefer the framework-owned .forge/venv/ (it has PyYAML
# pre-installed by `forge preflight enable-git-hook`). Fall back to bare
# `python3` only if the venv is missing — preflight will then fail noisily
# with a clear rebuild instruction if PyYAML isn't available.
FORGE_VENV_PY="${REPO_ROOT}/.forge/venv/bin/python"
if [[ -x "${FORGE_VENV_PY}" ]]; then
  PYTHON_BIN="${FORGE_VENV_PY}"
else
  PYTHON_BIN="python3"
fi

# Read in-progress tasks. If registry missing, default to running preflight
# (safer than silent skip on a fresh project).
TASKS_JSON="$("${PYTHON_BIN}" "${FORGE_PY}" --project-root "${REPO_ROOT}" task ls --in-progress --json 2>/dev/null || echo '[]')"

REQUIRED=$("${PYTHON_BIN}" -c "
import json, sys
tasks = json.loads('''${TASKS_JSON}''') if '''${TASKS_JSON}''' else []
if not tasks:
    # No in-progress tasks → run preflight as the safe default.
    print('yes')
    sys.exit(0)
needs = [t for t in tasks if t.get('preflight_required') is True]
print('yes' if needs else 'no')
" 2>/dev/null || echo "yes")

if [[ "${REQUIRED}" == "no" ]]; then
  echo "preflight: no in-progress task requires preflight — skipping" >&2
  exit 0
fi

# Validate the chosen Python has PyYAML before invoking preflight.py —
# the framework's workflow_parser imports yaml at module load time, and
# a "ModuleNotFoundError: No module named 'yaml'" buried in a traceback
# is a much worse UX than this explicit message.
if ! "${PYTHON_BIN}" -c "import yaml" >/dev/null 2>&1; then
  echo "preflight: ❌ PyYAML not available on ${PYTHON_BIN}" >&2
  echo "          run \`forge preflight enable-git-hook --force\` to (re)build .forge/venv/," >&2
  echo "          or set FORGE_SKIP_PREFLIGHT=1 to bypass this push" >&2
  exit 1
fi

echo "preflight: running local CI mirror …" >&2
if "${PYTHON_BIN}" "${PREFLIGHT_PY}" --project-root "${REPO_ROOT}" --quick; then
  exit 0
else
  echo "preflight: ❌ blocked push (re-run /preflight-ci for full output, or set FORGE_SKIP_PREFLIGHT=1 to override)" >&2
  exit 1
fi
