"""Generate local-runnable bash scripts from derived gating jobs.

Each gating job becomes one `.forge/preflight/<job>.sh` file containing:

    #!/usr/bin/env bash
    set -euo pipefail
    # Generated by /preflight-ci from <workflow file>
    # DO NOT EDIT — regenerate with `/preflight-ci --regenerate`

    export KEY=value          # one per env: entry
    ...

    # Step: <step name or index>
    <run: block>
    ...

A `drift.lock` file at `.forge/preflight/drift.lock` records SHA-256 of every
workflow file at generation time. On subsequent runs we compare the live
hashes against `drift.lock`; any mismatch is surfaced before execution.

Public API:
    generate_scripts(jobs, out_dir, workflows_dir) -> list[Path]
    compute_drift(workflows_dir, lockfile) -> DriftReport
    write_lockfile(workflows_dir, lockfile) -> None
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Iterable

# Run-as-script support: ISA verification + future direct invocations need
# this file to import siblings without requiring the package context.
sys.path.insert(0, str(Path(__file__).resolve().parent))

# workflow_parser imports `yaml`. Importing it at module top-level forces
# every consumer of script_generator (including unit tests for unrelated
# pure-Python helpers like `_rewrite_actions_templates`) to have PyYAML
# installed. Guard with TYPE_CHECKING for annotations and lazy-import the
# runtime helpers inside the functions that actually call them.
if TYPE_CHECKING:
    from workflow_parser import Job  # noqa: F401  (annotation use only)

SENTINEL_HEADER = "# Generated by /preflight-ci"

# GitHub Actions template syntax that maps cleanly to a local env var.
# `secrets.X`, `env.X`, `vars.X`, `inputs.X` — the user can plausibly
# `export X=...` before running the script. Other contexts (`github.*`,
# `steps.*.outputs.*`, `matrix.*`, function calls) are CI-only and pass
# through untouched.
#
# Both forms supported:
#   ${{ vars.X }}                     → ${X:-}
#   ${{ vars.X || '60' }}             → ${X:-60}
#   ${{ secrets.Y || "h:llo world" }} → ${Y:-h:llo world}
#   ${{ env.Z || bareword }}          → ${Z:-bareword}
# The fallback form is GitHub's documented best-practice pattern for
# workflow vars/secrets that should have sensible defaults.
_TEMPLATE_RE = re.compile(
    r"""
    \$\{\{\s*
    (?:secrets|env|vars|inputs)\.
    (?P<name>[A-Za-z_][A-Za-z0-9_]*)
    \s*
    (?:
        \|\|\s*
        (?:
            '(?P<default_sq>[^']*)'
          | "(?P<default_dq>[^"]*)"
          | (?P<default_bare>[^\s}|]+)
        )
        \s*
    )?
    \}\}
    """,
    re.VERBOSE,
)


def _rewrite_actions_templates(text: str) -> str:
    """Rewrite ${{ secrets|env|vars|inputs.NAME[ || 'default'] }} → ${NAME:-[default]}.

    Two reasons this matters:
      1. `${{ ... }}` is invalid bash syntax — generated scripts die with
         "bad substitution" when they hit it. `${NAME:-default}` is valid
         bash and gives the user a single export-able knob per secret.
      2. Emitting `${{ secrets.X }}` verbatim into a checked-in script
         trips gitleaks on the literal pattern, even though the value
         is never the real secret.

    The default (if present) is bash-escaped: `$` and backtick are made
    literal so a GHA default like `foo$bar` doesn't suddenly resolve as
    a bash variable.
    """

    def _sub(match: re.Match) -> str:
        name = match.group("name")
        default = (
            match.group("default_sq")
            if match.group("default_sq") is not None
            else match.group("default_dq")
            if match.group("default_dq") is not None
            else match.group("default_bare")
            if match.group("default_bare") is not None
            else ""
        )
        escaped_default = default.replace("\\", "\\\\").replace("$", "\\$").replace("`", "\\`")
        return f"${{{name}:-{escaped_default}}}"

    return _TEMPLATE_RE.sub(_sub, text)


def _shell_escape_double_quoted(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def _render_env_export(key: str, value: str, indent: str) -> str:
    """Render a single `export KEY="VALUE"` line, rewriting templates.

    Per-value branch — when the value contains a rewritable GHA template,
    rewrite it and skip `$`-escaping so the resulting `${KEY:-}` actually
    expands at runtime. Pure literal values keep full `$`-escaping so
    benign values like "p$word" don't suddenly resolve as bash variables.
    """
    if _TEMPLATE_RE.search(value):
        rewritten = _rewrite_actions_templates(value)
        escaped = (
            rewritten.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
        )
    else:
        escaped = _shell_escape_double_quoted(value)
    return f'{indent}export {key}="{escaped}"'


def render_script(
    job: Job,
    workflow_file: Path,
    env_files: list[str] | None = None,
) -> str:
    """Render the bash script body for one workflow Job.

    env_files (T497/T498): ordered list of project-relative paths the
    script should source before any `export`. Embedded at generation
    time, resolved at script-run time relative to cwd (project root).
    Order is base-first / override-last — every existing file is
    sourced (no `break`); later layers override earlier ones via bash
    last-export-wins semantics. Missing files are silently skipped so
    the script stays runnable when secrets aren't present.
    """
    lines: list[str] = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        f"{SENTINEL_HEADER} from {workflow_file}",
        f"# Job: {job.name}",
        "# DO NOT EDIT — regenerate with `/preflight-ci --regenerate`",
        "",
    ]

    # T497: source the dev's .env so password env-refs the Compose
    # introspector emitted (e.g. `${REDIS_PASSWORD:-}`) resolve to real
    # values at run time. Generator embeds candidate paths at gen time;
    # script picks the first that exists at run time. Wrapped in
    # `set +e` so a malformed .env line doesn't kill the whole preflight
    # job under `set -e`. `set -a` auto-exports every assignment so the
    # values reach the subshelled steps below. Placed BEFORE the shim
    # source because shims may themselves want env vars.
    if env_files:
        lines.append(
            "# T497/T498: layered .env merge so password env-refs resolve."
        )
        lines.append(
            "# Files listed base-first / override-last; every existing layer"
        )
        lines.append(
            "# is sourced (no `break`) so later layers override earlier ones"
        )
        lines.append(
            "# via bash last-export-wins semantics. Compose-installed .env is"
        )
        lines.append("# the base; root .env is the optional override.")
        # set +eu temporarily — set -e kills on the first malformed line,
        # set -u kills on inline ${UNDEF} substitution that's common in
        # .env files (e.g. `DATABASE_URL=postgres://$POSTGRES_USER@...`).
        # set -a auto-exports every assignment so the values reach
        # subshelled steps. Acceptance criterion: "if no .env is present,
        # script still runs" — the for-loop just exits with nothing found.
        lines.append("set +eu")
        lines.append("for _env_layer in \\")
        # shlex.quote each path: T502 absolute paths can contain whitespace
        # (macOS `Library/Application Support/...`) or shell metachars
        # (`*`, `?`, `[`, `'`). An unquoted token gets word-split and glob-
        # expanded by bash, so `_env_layer` iterates over fragments and the
        # `[ -f "$_env_layer" ]` check silently fails for every fragment.
        # `shlex.quote` is a no-op on common-case paths (`.env`,
        # `infrastructure/compose/.env`) so the rendered loop stays
        # unchanged for the 99% case.
        for ef in env_files[:-1]:
            lines.append(f"    {shlex.quote(ef)} \\")
        lines.append(f"    {shlex.quote(env_files[-1])}")
        lines.append("do")
        lines.append('  if [ -f "$_env_layer" ]; then')
        lines.append("    set -a")
        lines.append('    # shellcheck disable=SC1090')
        lines.append('    . "$_env_layer"')
        lines.append("    set +a")
        lines.append("  fi")
        lines.append("done")
        lines.append("set -eu")
        lines.append("")

    lines.extend([
        # Source project-local portability shims (e.g. `pip` -> `python3 -m pip`
        # when bare `pip` is missing on PATH). Ships empty by default; projects
        # extend it for their toolchain. No-op when the real binary is on PATH,
        # so CI runs unchanged. Placed after the banner so the user sees which
        # job is running before any shim-missing diagnostic fires.
        '_shim_path="$(dirname "${BASH_SOURCE[0]:-$0}")/_local_shims.sh"',
        'if [ ! -f "$_shim_path" ]; then',
        '  echo "ERROR: preflight portability shim missing at $_shim_path" >&2',
        '  echo "       run \\`/preflight-ci --regenerate\\` to restore it" >&2',
        '  exit 1',
        'fi',
        'source "$_shim_path"',
        "",
    ])
    if job.env:
        for k, v in job.env.items():
            lines.append(_render_env_export(k, str(v), indent=""))
        lines.append("")

    # Each step runs in its own subshell `( ... )` so side-effects like `cd`
    # do not leak into the next step — GitHub Actions runs each step in a
    # fresh shell, and the local mirror must match that isolation or steps
    # 2+ start in the cwd of step 1.
    for i, step in enumerate(job.steps):
        label = step.name or step.uses or f"step-{i}"
        if step.run is None:
            lines.append(f"# Skipped step: {label} (uses: {step.uses}, no local mirror)")
            continue
        lines.append(f"# Step: {label}")
        lines.append("(")
        for k, v in step.env.items():
            lines.append(_render_env_export(k, str(v), indent="  "))
        for run_line in _rewrite_actions_templates(step.run).splitlines():
            lines.append(f"  {run_line}")
        lines.append(")")
        lines.append("")
    return "\n".join(lines) + "\n"


def generate_scripts(
    jobs: Iterable[Job],
    out_dir: Path,
    project_root: Path | None = None,
) -> list[Path]:
    """Generate one .sh per job.

    When `project_root` is supplied, the generator looks for a Compose file
    under it and rewrites `localhost:CONTAINER` URLs in each job's env to
    the dev's Compose host ports — fixes the CI-vs-local port mismatch
    (T496) without per-machine `.git/hooks/pre-push` patches. Empty
    `*_PASSWORD` defaults that match a Compose service's password env are
    replaced with `${NAME:-}` env-var refs, never inlined values.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    # env_files: list of project-relative paths the generated script will
    # try to source before any `export`. Discovered here, embedded in
    # render_script. Empty list means no source-block is emitted (zero
    # cost when the project has no .env, no behavior change).
    env_files_rel: list[str] = []

    # password_refs_emitted: tracks whether the Compose introspector
    # substituted any empty `*_PASSWORD` defaults into `${{ env.NAME }}`
    # GHA templates. If yes, the script depends on .env-sourcing being
    # actually wired — otherwise the env-refs resolve empty at run time
    # and the source-block is silently load-bearing-but-broken. Used
    # below to decide whether to warn when no .env was discovered.
    password_refs_emitted = False
    compose_file: Path | None = None

    if project_root is not None:
        from compose_introspector import (
            discover_compose_file,
            discover_env_files,
            load_password_env,
            load_port_map,
            rewrite_env_for_compose,
        )

        compose_file = discover_compose_file(project_root)
        if compose_file is not None:
            port_map = load_port_map(compose_file)
            password_env = load_password_env(compose_file)
            if port_map or password_env:
                # Workflow env can sit at job level (`jobs.<j>.env`) OR step
                # level (`jobs.<j>.steps[].env`). Workflows in the wild often
                # put DATABASE_URL / REDIS_PASSWORD on the test step rather
                # than the job — we have to rewrite both surfaces or the
                # fix only half-lands.
                rewritten_jobs = []
                for j in jobs:
                    j.env = rewrite_env_for_compose(j.env, port_map, password_env)
                    for step in j.steps:
                        if step.env:
                            step.env = rewrite_env_for_compose(
                                step.env, port_map, password_env
                            )
                    rewritten_jobs.append(j)
                jobs = rewritten_jobs
                # Detect whether any password substitution actually fired.
                # The rewrite emits `${{ env.NAME }}` templates that the
                # later `_rewrite_actions_templates` pass turns into bash
                # `${NAME:-}`. If any rewritten env value carries that
                # marker, the source-block is load-bearing.
                password_refs_emitted = any(
                    "${{ env." in str(v)
                    for j in jobs
                    for v in list(j.env.values()) + [
                        sv for step in j.steps for sv in step.env.values()
                    ]
                )

        # T497/T498/T499: discover the dev's .env files so the generated
        # script can source them at run time to resolve the password
        # env-refs the rewrite emitted. compose_file is passed so the
        # discovery can also try ".env" next to the compose file (catches
        # non-canonical compose layouts without needing a pyproject.toml
        # opt-in). Embedded as project-relative paths (POSIX) so the
        # script works from any clone with the same project layout.
        env_paths = discover_env_files(project_root, compose_file=compose_file)
        # T502: a symlinked .env (or absolute pyproject.toml override) may
        # resolve outside project_root — `Path.relative_to` raises ValueError
        # in that case. Fall back to the resolved absolute path; the
        # generated script's `[ -f "$_env_layer" ]` check works either way.
        # Generated scripts are gitignored, so an operator-specific absolute
        # path doesn't damage portability — each operator regenerates locally.
        env_files_rel: list[str] = []
        outside_paths: list[Path] = []
        project_root_resolved = project_root.resolve()
        for ef in env_paths:
            resolved = ef.resolve()
            try:
                env_files_rel.append(
                    resolved.relative_to(project_root_resolved).as_posix()
                )
            except ValueError:
                env_files_rel.append(resolved.as_posix())
                outside_paths.append(resolved)
        if outside_paths:
            joined = ", ".join(str(p) for p in outside_paths)
            print(
                "warning: preflight env file(s) resolve outside project "
                f"root: {joined}. Generated script will source via absolute "
                "path — it still works on this machine, but the path is "
                "operator-machine-specific; other operators must regenerate.",
                file=sys.stderr,
            )

        # T499: when the script relies on .env-sourced password values
        # but no .env was discovered, the generated script will silently
        # fail at run time with empty env-refs. Surface a one-line hint
        # at generation time so the consumer can opt into a non-canonical
        # location via pyproject.toml. Only fires when the source-block
        # is load-bearing — projects without password-rewrites stay
        # quiet.
        if password_refs_emitted and not env_paths:
            print(
                "warning: preflight generated password env-refs from "
                "Compose introspection, but no .env was found at canonical "
                "paths (.env, infrastructure/compose/.env, compose/.env, "
                "or next to the discovered compose file). At run time the "
                "env-refs will resolve empty and DB auth will fail. Opt "
                "into a non-canonical .env location via pyproject.toml:\n"
                "    [tool.forge.preflight]\n"
                '    env_files = ["path/to/your/.env"]',
                file=sys.stderr,
            )

    written: list[Path] = []
    for job in jobs:
        script_path = out_dir / f"{job.name}.sh"
        script_path.write_text(
            render_script(job, Path(job.file), env_files=env_files_rel or None)
        )
        script_path.chmod(0o755)
        written.append(script_path)
    return written


# --- Drift detection ---------------------------------------------------------

@dataclass
class DriftReport:
    changed: list[str]
    new: list[str]
    removed: list[str]

    @property
    def has_drift(self) -> bool:
        return bool(self.changed or self.new or self.removed)


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _collect_workflow_hashes(workflows_dir: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not workflows_dir.exists():
        return out
    files = list(workflows_dir.glob("*.yml")) + list(workflows_dir.glob("*.yaml"))
    for f in sorted(files):
        out[f.name] = _hash_file(f)
    return out


def write_lockfile(workflows_dir: Path, lockfile: Path) -> None:
    hashes = _collect_workflow_hashes(workflows_dir)
    lockfile.parent.mkdir(parents=True, exist_ok=True)
    lockfile.write_text(json.dumps({"workflow_hashes": hashes}, indent=2, sort_keys=True))


def compute_drift(workflows_dir: Path, lockfile: Path) -> DriftReport:
    live = _collect_workflow_hashes(workflows_dir)
    if not lockfile.exists():
        return DriftReport(changed=[], new=sorted(live.keys()), removed=[])
    locked = json.loads(lockfile.read_text()).get("workflow_hashes", {})
    changed = sorted(k for k in live if k in locked and live[k] != locked[k])
    new = sorted(k for k in live if k not in locked)
    removed = sorted(k for k in locked if k not in live)
    return DriftReport(changed=changed, new=new, removed=removed)


# --- CLI ---------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="script_generator")
    p.add_argument("workflows_dir", type=Path)
    p.add_argument("--out", type=Path, required=True, help="Output dir (e.g. .forge/preflight)")
    p.add_argument("--default-branch", default="main")
    p.add_argument("--protection-mock", type=Path)
    p.add_argument("--check-drift", action="store_true", help="Report drift; do not generate")
    p.add_argument(
        "--project-root",
        type=Path,
        default=None,
        help=(
            "Project root for Compose introspection. Default: parent of "
            "--out's parent (i.e. <root>/.forge/preflight → <root>)."
        ),
    )
    p.add_argument("--json", action="store_true")
    args = p.parse_args(argv)

    lockfile = args.out / "drift.lock"

    if args.check_drift:
        report = compute_drift(args.workflows_dir, lockfile)
        payload = {
            "has_drift": report.has_drift,
            "changed": report.changed,
            "new": report.new,
            "removed": report.removed,
        }
        if args.json:
            print(json.dumps(payload, indent=2))
        else:
            if report.has_drift:
                print("⚠️ Preflight drift detected")
                if report.changed:
                    print(f"  changed: {', '.join(report.changed)}")
                if report.new:
                    print(f"  new: {', '.join(report.new)}")
                if report.removed:
                    print(f"  removed: {', '.join(report.removed)}")
            else:
                print("✓ No drift")
        return 2 if report.has_drift else 0

    # Lazy import — workflow_parser pulls in PyYAML. Keeping it out of the
    # module-top means pure helpers in this file (e.g. _rewrite_actions_templates)
    # are testable on any Python without PyYAML installed.
    from workflow_parser import derive_gating_jobs, load_protection_required

    required = None
    if args.protection_mock and args.protection_mock.exists():
        required = load_protection_required(args.protection_mock)
    jobs = derive_gating_jobs(args.workflows_dir, args.default_branch, required)
    # Compose introspection (T496): the dev's running Compose stack is the
    # ground truth for service host ports. Resolve the project root from
    # `--out` (`<project_root>/.forge/preflight`) so the generator can find
    # `docker-compose.yml` and rewrite container-port literals from the
    # workflow into the dev's actual host-port mappings.
    project_root = args.project_root or args.out.resolve().parent.parent
    written = generate_scripts(jobs, args.out, project_root=project_root)
    write_lockfile(args.workflows_dir, lockfile)

    if args.json:
        print(json.dumps([str(p) for p in written], indent=2))
    else:
        for p in written:
            print(f"wrote {p}")
        print(f"wrote {lockfile}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
