"""Generate local-runnable bash scripts from derived gating jobs.

Each gating job becomes one `.forge/preflight/<job>.sh` file containing:

    #!/usr/bin/env bash
    set -euo pipefail
    # Generated by /preflight-ci from <workflow file>
    # DO NOT EDIT — regenerate with `/preflight-ci --regenerate`

    export KEY=value          # one per env: entry
    ...

    # Step: <step name or index>
    <run: block>
    ...

A `drift.lock` file at `.forge/preflight/drift.lock` records SHA-256 of every
workflow file at generation time. On subsequent runs we compare the live
hashes against `drift.lock`; any mismatch is surfaced before execution.

Public API:
    generate_scripts(jobs, out_dir, workflows_dir) -> list[Path]
    compute_drift(workflows_dir, lockfile) -> DriftReport
    write_lockfile(workflows_dir, lockfile) -> None
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shlex
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Iterable

# Run-as-script support: ISA verification + future direct invocations need
# this file to import siblings without requiring the package context.
sys.path.insert(0, str(Path(__file__).resolve().parent))

# workflow_parser imports `yaml`. Importing it at module top-level forces
# every consumer of script_generator (including unit tests for unrelated
# pure-Python helpers like `_rewrite_actions_templates`) to have PyYAML
# installed. Guard with TYPE_CHECKING for annotations and lazy-import the
# runtime helpers inside the functions that actually call them.
if TYPE_CHECKING:
    from workflow_parser import Job  # noqa: F401  (annotation use only)

SENTINEL_HEADER = "# Generated by /preflight-ci"

# Contract between a generated job and the runner that reports on it.
#
# A job that finds its infra dependency absent echoes this prefix and exits 0,
# so an absent local stack never blocks a push. Exit 0 alone is indistinguishable
# from a pass, so preflight.py sniffs for this marker and reports the job as
# SKIPPED rather than green. Two rules, both load-bearing:
#
#   1. Echo it to STDERR. The runner reads stderr only — a guard that echoes to
#      stdout is undetected and silently renders as a plain green.
#   2. It means the WHOLE job skipped. A job that emits it and then does real
#      work is misreported as having contributed no coverage.
#
# Defined here, on the emitting side, and imported by preflight.py — one literal,
# so a reworded echo cannot silently break detection.
#
# Namespaced deliberately. A bare `SKIP: ` is matched against the stderr of every
# third-party tool in every generated job, and it is a natural phrase — this repo
# already emits `SKIP: <dir> — <reason>` from a non-preflight script for a
# *partial* skip. A false positive here reports a job that fully ran as having
# contributed nothing, and enough of those train the reader to ignore the line,
# which is how this whole mechanism dies.
JOB_SKIP_MARKER = "FORGE_SKIP: "

# Bump whenever the SEMANTICS of a generated script change in a way the runner
# depends on — the skip-marker literal, the guard shape, anything the runner
# parses back out. `.forge/preflight/*.sh` is gitignored and regenerated only on
# workflow drift, an explicit --regenerate, or a missing lockfile, so without
# this an existing checkout keeps running scripts built against the OLD contract
# while the new runner expects the new one. That is not a cosmetic mismatch: when
# the marker changed, stale scripts emitted `SKIP: ` while the runner looked for
# `FORGE_SKIP: `, so a skipped job went undetected and reported green again —
# the exact bug this machinery exists to prevent, reintroduced by the upgrade.
# A mismatch here forces regeneration automatically (see run_preflight); it is
# framework-internal, so it must not make the user run a command to recover.
# 4: tracked step subshells no longer sit on the LHS of `||`, which suppressed
#    errexit inside the body and let a multi-command step report green after an
#    early command failed. Stale scripts still carry the old shape, so this must
#    force regeneration.
# 5: `if: false` steps are emitted as `# Disabled step:` and omitted, instead of
#    over-run. Stale scripts still RUN work CI suppresses.
# 6: destructive commands (volume prunes, compose teardowns that take volumes,
#    recursive deletes of the filesystem root) are refused at generation time
#    rather than transcribed. Stale scripts still CONTAIN them, and any
#    env-keyed guard around them is armed by the workflow `env:` block the
#    generator itself exports — so this must force regeneration.
# 7: a job containing a destructive step is skipped ENTIRELY (JOB_SKIP_MARKER),
#    not just missing that step. The refused step often establishes the job's
#    precondition, so running the remainder reports a green that tested nothing.
GENERATOR_CONTRACT = 7

# --- step `if:` conditions ---------------------------------------------------
# GitHub runs a step only when its `if:` holds, with an implicit `success()`
# when absent. The mirror dropped the condition entirely, which was wrong in
# three separate directions at once:
#
#   - `always()` / `!cancelled()` cleanup was killed by `set -e` at exactly the
#     moment it exists for — a failed E2E run left the compose stack and its
#     volumes up, and the "capture container state on failure" diagnostics that
#     would explain the failure never printed.
#   - `failure()` steps ran on the SUCCESS path, where CI never runs them.
#   - Steps gated on a prior step's output ran with no such output — including,
#     in one real workflow, a `git add` / `git commit` / `git push` step gated on
#     `github.event_name == 'push'`. The local mirror would push to whatever
#     branch the developer had checked out.
#
# Unrecognised conditions split by WHAT they gate on, because the two classes
# fail in opposite directions:
#
#   - Change detection (`steps.<id>.outputs.*`, `hashFiles(...)`) is an
#     optimisation: CI skips work when nothing relevant changed. Running it
#     anyway locally is a superset — slower, never wrong — and these steps
#     genuinely gate (the CHANGELOG and CORS drift checks live behind
#     paths-filter outputs). Omitting them would take working local coverage
#     away, so they are over-approximated to "always run".
#   - Context selection (`github.*`) picks a different execution context, not
#     more work. Running it anyway does work meant for another context — one
#     such step runs `git add` / `git commit` / `git push` under
#     `github.event_name == 'push'`, which would push the developer's branch.
#     These are omitted, and named so the omission is visible.
#
# A condition mentioning `github.` anywhere is context-gated even if it also
# mentions step outputs: `steps.x.outputs.y == 'true' && github.event_name ==
# 'push'` is exactly the git-push step, and the github half is the dangerous one.
_ALWAYS_CONDITIONS = frozenset({"always()", "!cancelled()", "! cancelled()"})
_FAILURE_CONDITIONS = frozenset({"failure()"})
_SUCCESS_CONDITIONS = frozenset({"success()"})

# `if: false` / `${{ false }}` — a step switched off on purpose rather than
# deleted. `Step.from_dict` normalizes the YAML boolean to the string "false",
# so both spellings land here. This must NOT fall through to the over-run
# default: over-running is only safe for change-DETECTION conditions, where
# running anyway is a superset. A disabled step is the opposite — CI suppresses
# it deliberately, so running it locally does work nobody asked for.
_NEVER_CONDITIONS = frozenset({"false"})

# Marks a condition as selecting an execution context rather than detecting a
# change. Deliberately a substring test on the context name — `github.ref`,
# `github.event_name`, `github.actor` all qualify, and a new one nobody
# anticipated still lands on the safe side.
_CONTEXT_MARKER = "github."

# `${{ ... }}` wrapping the whole expression is equivalent to the bare form.
_WRAPPED_EXPR_RE = re.compile(r"^\$\{\{\s*(?P<inner>.*?)\s*\}\}$", re.DOTALL)

# How a step's condition maps onto the generated script.
STEP_NORMAL = "normal"          # run only while nothing has failed (GHA default)
STEP_ALWAYS = "always"          # run even after an earlier step failed
STEP_ON_FAILURE = "on-failure"  # run only when an earlier step failed
STEP_OVER_RUN = "over-run"      # can't evaluate, but running anyway is a superset
STEP_NEVER = "never"            # `if: false` — CI never runs it, so neither do we
STEP_UNTRANSLATABLE = None      # can't evaluate and running anyway is unsafe


def classify_condition(condition: str | None) -> str | None:
    """Map a step's raw `if:` to an emission mode.

    The CI-status functions translate exactly, because they depend on nothing
    but the run itself. Everything else depends on state the mirror does not
    have, and is split by which way guessing wrong hurts — see the notes on
    `_CONTEXT_MARKER` above.
    """
    if condition is None:
        return STEP_NORMAL
    expr = condition.strip()
    m = _WRAPPED_EXPR_RE.match(expr)
    if m:
        expr = m.group("inner").strip()
    normalized = " ".join(expr.split())
    if normalized in _ALWAYS_CONDITIONS:
        return STEP_ALWAYS
    if normalized in _FAILURE_CONDITIONS:
        return STEP_ON_FAILURE
    if normalized in _SUCCESS_CONDITIONS:
        return STEP_NORMAL
    if normalized in _NEVER_CONDITIONS:
        return STEP_NEVER
    if _CONTEXT_MARKER in normalized:
        return STEP_UNTRANSLATABLE
    return STEP_OVER_RUN


# `uses:` steps cannot run locally, so they are emitted as inert comments. Most
# of those are harmless — but a job whose actual gating work IS a `uses:` step
# still runs its `run:` steps, exits 0, and reports a clean green having done
# nothing. `image-scan` is the live example: it builds two Docker images and
# scans neither, because both trivy steps are comments.
#
# Classification is a DENYLIST of locally-inert actions, not an allowlist of
# dangerous ones, so an unrecognised action counts as lost work. Over-warning is
# recoverable; under-warning is the bug.
#
# Inert means one of two things, and nothing else:
#   - it prepares the environment (checkout, language/toolchain setup, cache,
#     buildx) — locally the environment is already there;
#   - it ships results OUT of CI (artifact upload, coverage upload) — no gating
#     signal is lost by not doing it.
# Anything that brings data IN that later steps consume, or that performs the
# check itself, is NOT inert: dropping it changes what the job proves.
LOCALLY_INERT_ACTIONS = frozenset({
    "actions/checkout",
    "actions/setup-python",
    "actions/setup-node",
    "actions/setup-java",
    "actions/setup-go",
    "actions/cache",
    "actions/upload-artifact",
    "docker/setup-buildx-action",
    "docker/setup-qemu-action",
    "codecov/codecov-action",
})

# Matches the `# Skipped step: <label> (uses: <action>@<ref>, no local mirror)`
# line emitted below. Parsed back by preflight.py — defined here, beside the
# emitter, so the two cannot drift (same reasoning as JOB_SKIP_MARKER).
_SKIPPED_STEP_RE = re.compile(
    r"^# Skipped step: (?P<label>.*?) \(uses: (?P<uses>\S+?), no local mirror\)$",
    re.MULTILINE,
)

# The other reason a step is omitted: its `if:` cannot be evaluated locally.
_SKIPPED_COND_RE = re.compile(
    r"^# Skipped step: (?P<label>.*?) "
    r"\(if: (?P<cond>.*?), condition not evaluable locally\)$",
    re.MULTILINE,
)

# Commands that are free to run on an ephemeral runner and expensive on a
# workstation. `run:` bodies are transcribed VERBATIM into scripts the developer
# executes against their real daemon, so this is the one physical chokepoint
# where "never mirror this locally" can be enforced.
#
# Why here and not with an `if [ "$CI" = true ]` guard in the workflow: the
# generator exports workflow- and job-level `env:` at the TOP of the mirror,
# above every step body. So any env-keyed guard is armed by the very thing an
# untrusted PR is allowed to edit — two lines in an `env:` block re-arm it, and
# preflight on that branch then runs it on the maintainer's machine. A command
# that is never written to the file cannot be re-armed by any variable. The same
# property rules out every "runner-only" variable as key material: `CI`,
# `GITHUB_ACTIONS`, `RUNNER_ENVIRONMENT`, `GITHUB_RUN_ID` are all either settable
# through `env:` or absent when the script is run directly.
#
# Deliberately narrow. Compose `down` WITHOUT a volume flag is not here: it stops
# containers and keeps volumes, which is recoverable, and refusing it would
# remove real local coverage. The line is drawn at "destroys data or reaches
# outside this project". Knowingly omitted, as judgement calls rather than
# oversights: `docker network prune` (cheap to recreate) and `git clean -xfd`
# (destructive, but a routine and deliberate local command).
#
# Prefer adding a pattern over relaxing one.
_DESTRUCTIVE_PATTERNS = [
    # Both binaries: the hyphenated v1 form is still in plenty of workflows.
    (re.compile(r"\bdocker[\s-]+volume\s+prune\b"), "docker volume prune"),
    (re.compile(r"\bdocker[\s-]+system\s+prune\b"), "docker system prune"),
    (re.compile(r"\bdocker[\s-]+volume\s+rm\b"), "docker volume rm"),
    # Volume flag in either order and either spelling:
    # `down -v --remove-orphans`, `down --volumes`.
    (re.compile(r"\bdocker[\s-]+compose\b[^\n]*\bdown\b[^\n]*(?:\s-\w*v\w*\b|--volumes\b)"),
     "docker compose down -v"),
    # Recursive delete of the filesystem root, with an optional trailing glob
    # since `<root>/*` destroys exactly as much as `<root>`.
    #
    # The recursive flag is found by LOOKAHEAD across the whole flag run, not by
    # position. Requiring the token adjacent to the target to carry `r`/`R` made
    # flag ORDER load-bearing: `rm -f -r /` matched while `rm -r -f /` did not —
    # the same command with the flags swapped. Separated flags are ordinary
    # shell, not an evasion attempt.
    (re.compile(
        r"\brm\s+"                                        # the command
        r"(?=(?:-\S+\s+)*(?:-\w*[rR]\w*|--recursive)\b)"  # recursive ANYWHERE in the flags
        r"(?:-\S+\s+)+"                                   # consume the flag run
        r"/\*?(?:\s|$)"                                   # target is the filesystem root
    ), "rm -rf /"),
]


# A shell line continuation is invisible to bash but fatal to every pattern
# above: `docker volume \<newline>  prune -f` is one command to the shell, yet
# the backslash breaks `\s+` and the newline stops the compose pattern's
# `[^\n]*`. Joining continuations BEFORE matching is the one normalization that
# covers all five patterns — and any future one — instead of teaching each
# regex about backslashes. Over-joining (a literal `\\` at end of line) only
# makes the denylist more eager, which is the safe direction for a refusal.
_LINE_CONTINUATION = re.compile(r"\\\r?\n\s*")


def destructive_commands(body: str) -> list[str]:
    """Names of destructive commands present in a workflow `run:` body."""
    joined = _LINE_CONTINUATION.sub(" ", body)
    return [name for pattern, name in _DESTRUCTIVE_PATTERNS if pattern.search(joined)]


def _sanitize_label(label: str) -> str:
    """Collapse an untrusted workflow label to one bounded, printable line.

    Belt to `shlex.quote`'s braces: quoting alone already makes the label inert,
    but a label carrying newlines would still emit extra stderr lines around the
    skip marker the runner parses. One line, bounded length, no control chars.
    """
    flattened = " ".join(str(label).split())
    printable = "".join(c for c in flattened if c.isprintable())
    return (printable[:80] + "…") if len(printable) > 80 else (printable or "(unnamed step)")


def dropped_gating_steps(script_text: str) -> list[str]:
    """Steps omitted from a generated script that carried real work.

    Two causes, both reported: a `uses:` step with no local mirror, and a step
    whose `if:` cannot be evaluated locally. Returns one
    ``"<label> (<reason>)"`` per omitted step.

    `uses:` steps that only prepare the environment or upload results are
    excluded — that is the common case, so a clean job stays visibly clean.
    Untranslatable conditions are never excluded: unlike a well-known action,
    there is no way to tell a cosmetic condition from a gating one.
    """
    found = []
    for m in _SKIPPED_STEP_RE.finditer(script_text):
        action = m.group("uses").split("@", 1)[0]
        if action in LOCALLY_INERT_ACTIONS:
            continue
        found.append(f'{m.group("label")} ({action})')
    for m in _SKIPPED_COND_RE.finditer(script_text):
        found.append(f'{m.group("label")} (if: {m.group("cond")})')
    return found

# GitHub Actions template syntax that maps cleanly to a local env var.
# `secrets.X`, `env.X`, `vars.X`, `inputs.X` — the user can plausibly
# `export X=...` before running the script. Other contexts (`github.*`,
# `steps.*.outputs.*`, `matrix.*`, function calls) are CI-only and pass
# through untouched.
#
# Both forms supported:
#   ${{ vars.X }}                     → ${X:-}
#   ${{ vars.X || '60' }}             → ${X:-60}
#   ${{ secrets.Y || "h:llo world" }} → ${Y:-h:llo world}
#   ${{ env.Z || bareword }}          → ${Z:-bareword}
# The fallback form is GitHub's documented best-practice pattern for
# workflow vars/secrets that should have sensible defaults.
_TEMPLATE_RE = re.compile(
    r"""
    \$\{\{\s*
    (?:secrets|env|vars|inputs)\.
    (?P<name>[A-Za-z_][A-Za-z0-9_]*)
    \s*
    (?:
        \|\|\s*
        (?:
            '(?P<default_sq>[^']*)'
          | "(?P<default_dq>[^"]*)"
          | (?P<default_bare>[^\s}|]+)
        )
        \s*
    )?
    \}\}
    """,
    re.VERBOSE,
)


def _rewrite_actions_templates(text: str) -> str:
    """Rewrite ${{ secrets|env|vars|inputs.NAME[ || 'default'] }} → ${NAME:-[default]}.

    Two reasons this matters:
      1. `${{ ... }}` is invalid bash syntax — generated scripts die with
         "bad substitution" when they hit it. `${NAME:-default}` is valid
         bash and gives the user a single export-able knob per secret.
      2. Emitting `${{ secrets.X }}` verbatim into a checked-in script
         trips gitleaks on the literal pattern, even though the value
         is never the real secret.

    The default (if present) is bash-escaped: `$` and backtick are made
    literal so a GHA default like `foo$bar` doesn't suddenly resolve as
    a bash variable.
    """

    def _sub(match: re.Match) -> str:
        name = match.group("name")
        default = (
            match.group("default_sq")
            if match.group("default_sq") is not None
            else match.group("default_dq")
            if match.group("default_dq") is not None
            else match.group("default_bare")
            if match.group("default_bare") is not None
            else ""
        )
        escaped_default = default.replace("\\", "\\\\").replace("$", "\\$").replace("`", "\\`")
        return f"${{{name}:-{escaped_default}}}"

    return _TEMPLATE_RE.sub(_sub, text)


def _shell_escape_double_quoted(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def _render_env_export(key: str, value: str, indent: str) -> str:
    """Render a single `export KEY="VALUE"` line, rewriting templates.

    Per-value branch — when the value contains a rewritable GHA template,
    rewrite it and skip `$`-escaping so the resulting `${KEY:-}` actually
    expands at runtime. Pure literal values keep full `$`-escaping so
    benign values like "p$word" don't suddenly resolve as bash variables.
    """
    if _TEMPLATE_RE.search(value):
        rewritten = _rewrite_actions_templates(value)
        escaped = (
            rewritten.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
        )
    else:
        escaped = _shell_escape_double_quoted(value)
    return f'{indent}export {key}="{escaped}"'


def _job_needs_postgres(job: Job) -> bool:
    """True when the job's env or any step references DATABASE_URL.

    Used to decide whether to emit the pg-reachability guard. A job that never
    touches DATABASE_URL (lint, changelog, frontend-only test steps) must NOT
    be gated on postgres — only jobs that would ERROR at a DB fixture when the
    stack is absent get the clean-skip guard.
    """
    if any("DATABASE_URL" in str(k) for k in job.env):
        return True
    for step in job.steps:
        if any("DATABASE_URL" in str(k) for k in step.env):
            return True
        if step.run and "DATABASE_URL" in step.run:
            return True
    return False


# postgresql://user:pw@HOST:PORT/db — capture HOST and optional :PORT.
_DB_HOST_PORT_RE = re.compile(r"@(?P<host>[^@/:\s]+)(?::(?P<port>\d+))?/")


def _job_db_host_port(job: Job) -> tuple[str, str] | None:
    """Extract (host, port) from the first resolved DATABASE_URL in the job.

    The Compose introspector has already rewritten DATABASE_URL's port to the
    dev's host-port mapping by the time render_script runs, so the value here
    carries the ground-truth host:port the DB steps will actually use. Emitting
    it as FORGE_PG_HOST/FORGE_PG_PORT lets the runtime probe reach the RIGHT
    server without depending on DATABASE_URL being in scope at guard time (it
    is exported per-step, inside subshells, AFTER the guard).

    Returns None when no literal DATABASE_URL value is found (e.g. a pure
    `${VAR}` ref) — the runtime helper then keeps its default. Port defaults to
    "5432" when the URL omits it.

    Scans job env, step env, AND step `run:` bodies — the last because a step
    may inline `export DATABASE_URL=postgresql://…`, and _job_needs_postgres()
    marks such a job DB-dependent, so the extractor must cover the same surface
    or the guard emits no FORGE_PG_* and the probe falls back to its default.
    """
    candidates: list[str] = []
    for k, v in job.env.items():
        if "DATABASE_URL" in str(k):
            candidates.append(str(v))
    for step in job.steps:
        for k, v in step.env.items():
            if "DATABASE_URL" in str(k):
                candidates.append(str(v))
        # Only mine the run body when it actually references DATABASE_URL, so an
        # unrelated postgresql:// URL elsewhere isn't mistaken for the DB target.
        if step.run and "DATABASE_URL" in step.run:
            candidates.append(step.run)
    for value in candidates:
        m = _DB_HOST_PORT_RE.search(value)
        if m:
            return m.group("host"), (m.group("port") or "5432")
    return None


def render_script(
    job: Job,
    workflow_file: Path,
    env_files: list[str] | None = None,
) -> str:
    """Render the bash script body for one workflow Job.

    env_files (T497/T498): ordered list of project-relative paths the
    script should source before any `export`. Embedded at generation
    time, resolved at script-run time relative to cwd (project root).
    Order is base-first / override-last — every existing file is
    sourced (no `break`); later layers override earlier ones via bash
    last-export-wins semantics. Missing files are silently skipped so
    the script stays runnable when secrets aren't present.
    """
    lines: list[str] = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        f"{SENTINEL_HEADER} from {workflow_file}",
        f"# Job: {job.name}",
        "# DO NOT EDIT — regenerate with `/preflight-ci --regenerate`",
        "",
    ]

    # T497: source the dev's .env so password env-refs the Compose
    # introspector emitted (e.g. `${REDIS_PASSWORD:-}`) resolve to real
    # values at run time. Generator embeds candidate paths at gen time;
    # script picks the first that exists at run time. Wrapped in
    # `set +e` so a malformed .env line doesn't kill the whole preflight
    # job under `set -e`. `set -a` auto-exports every assignment so the
    # values reach the subshelled steps below. Placed BEFORE the shim
    # source because shims may themselves want env vars.
    if env_files:
        lines.append(
            "# T497/T498: layered .env merge so password env-refs resolve."
        )
        lines.append(
            "# Files listed base-first / override-last; every existing layer"
        )
        lines.append(
            "# is sourced (no `break`) so later layers override earlier ones"
        )
        lines.append(
            "# via bash last-export-wins semantics. Compose-installed .env is"
        )
        lines.append("# the base; root .env is the optional override.")
        # set +eu temporarily — set -e kills on the first malformed line,
        # set -u kills on inline ${UNDEF} substitution that's common in
        # .env files (e.g. `DATABASE_URL=postgres://$POSTGRES_USER@...`).
        # set -a auto-exports every assignment so the values reach
        # subshelled steps. Acceptance criterion: "if no .env is present,
        # script still runs" — the for-loop just exits with nothing found.
        lines.append("set +eu")
        lines.append("for _env_layer in \\")
        # shlex.quote each path: T502 absolute paths can contain whitespace
        # (macOS `Library/Application Support/...`) or shell metachars
        # (`*`, `?`, `[`, `'`). An unquoted token gets word-split and glob-
        # expanded by bash, so `_env_layer` iterates over fragments and the
        # `[ -f "$_env_layer" ]` check silently fails for every fragment.
        # `shlex.quote` is a no-op on common-case paths (`.env`,
        # `infrastructure/compose/.env`) so the rendered loop stays
        # unchanged for the 99% case.
        for ef in env_files[:-1]:
            lines.append(f"    {shlex.quote(ef)} \\")
        lines.append(f"    {shlex.quote(env_files[-1])}")
        lines.append("do")
        lines.append('  if [ -f "$_env_layer" ]; then')
        lines.append("    set -a")
        lines.append('    # shellcheck disable=SC1090')
        lines.append('    . "$_env_layer"')
        lines.append("    set +a")
        lines.append("  fi")
        lines.append("done")
        lines.append("set -eu")
        lines.append("")

    lines.extend([
        # Source project-local portability shims (e.g. `pip` -> `python3 -m pip`
        # when bare `pip` is missing on PATH). Ships empty by default; projects
        # extend it for their toolchain. No-op when the real binary is on PATH,
        # so CI runs unchanged. Placed after the banner so the user sees which
        # job is running before any shim-missing diagnostic fires.
        '_shim_path="$(dirname "${BASH_SOURCE[0]:-$0}")/_local_shims.sh"',
        'if [ ! -f "$_shim_path" ]; then',
        '  echo "ERROR: preflight portability shim missing at $_shim_path" >&2',
        '  echo "       run \\`/preflight-ci --regenerate\\` to restore it" >&2',
        '  exit 1',
        'fi',
        'source "$_shim_path"',
        "",
    ])
    if job.env:
        for k, v in job.env.items():
            lines.append(_render_env_export(k, str(v), indent=""))
        lines.append("")

    # pg-reachability guard. Jobs referencing DATABASE_URL ERROR at the DB
    # fixture when the compose stack is absent (a cred-cascade that reads as
    # test debt but is pure env). Mirror the integration-lane self-skip
    # discipline: probe postgres and, if unreachable, skip the whole job with a
    # clear reason (exit 0) instead of running pytest into a wall of connection
    # ERRORs. CI always has its service up, so the guard is a no-op there.
    if _job_needs_postgres(job):
        lines.extend([
            "# Skip cleanly when the compose postgres is unreachable (stack",
            "# absent) rather than ERRORing every DB test on a bad connection.",
        ])
        # Feed the probe the host:port the DB steps will actually use. Steps
        # export DATABASE_URL per-step INSIDE their subshells (after this
        # guard), so the helper can't read it at guard time; extract it at
        # generation time (Compose-rewritten value = ground truth).
        hp = _job_db_host_port(job)
        if hp is not None:
            host, port = hp
            lines.append(f'export FORGE_PG_HOST="{host}" FORGE_PG_PORT="{port}"')
        # `declare -F` first: _local_shims.sh is seeded only-if-missing, so an
        # install predating the helper still has a shim without it. An
        # unguarded call would exit 127 -> `!` -> true -> silently skip EVERY
        # DB job. Absent helper must mean "run", never "skip".
        lines.extend([
            "if declare -F _forge_pg_reachable >/dev/null && "
            "! _forge_pg_reachable; then",
            f'  echo "{JOB_SKIP_MARKER}postgres not reachable (compose stack '
            'down) — skipping ${0##*/} (DB-dependent job). Bring the stack up '
            '(docker compose up -d) to run it." >&2',
            "  exit 0",
            "fi",
            "",
        ])

    # Each step runs in its own subshell `( ... )` so side-effects like `cd`
    # do not leak into the next step — GitHub Actions runs each step in a
    # fresh shell, and the local mirror must match that isolation or steps
    # 2+ start in the cwd of step 1.
    #
    # GitHub Actions applies `defaults.run.working-directory` (workflow or job
    # level) to every `run` step, and a step's own `working-directory` wins
    # over that. Without this, a job that declares `working-directory: backend`
    # runs `run:` commands from the repo root locally — e.g. `ruff check app/`
    # fails with "No such file or directory" because app/ lives under backend/.
    # The path is relative to the repo root (where the mirror is invoked), so a
    # relative `cd` at the top of each subshell reproduces GHA's cwd exactly.
    # A job containing a status-conditional step needs GitHub's step semantics,
    # which `set -e` cannot express: a failed step must not abort the script,
    # because `always()` / `failure()` steps still have to run — while normal
    # steps after a failure must still be skipped, and the job must still end
    # red. That needs an explicit failure flag, so it is emitted only for jobs
    # that actually have such a step; every other job keeps the simpler
    # `set -e` shape and its generated script is unchanged.
    modes = [
        classify_condition(s.if_condition) for s in job.steps if s.run is not None
    ]
    tracks_failure = any(m in (STEP_ALWAYS, STEP_ON_FAILURE) for m in modes)
    if tracks_failure:
        lines.extend([
            "# This job has status-conditional steps, so a failing step must not",
            "# abort the script — later always()/failure() steps still need to run.",
            "# Failure is recorded and re-raised as the exit status at the end.",
            "_forge_failed=0",
            "",
        ])

    # Refusing only the STEP was the first cut and it was wrong. In a
    # fresh-install gate the refused cleanup is what establishes the job's
    # precondition — an empty volume. Drop just that step and the remainder still
    # runs, against RETAINED volumes, taking the install-recovery path and
    # reporting a clean green without ever exercising a fresh install. That is
    # the "gate reports green having tested nothing" failure this whole mechanism
    # exists to prevent.
    #
    # Skipping the whole job is the honest outcome: its precondition cannot be
    # established locally without doing the very thing we refuse. This uses the
    # same JOB_SKIP_MARKER the DB-reachability guard uses, so the runner reports
    # it as SKIPPED (coverage that did not run) rather than as a pass.
    # `classify_condition` is consulted here because the renderer below omits
    # STEP_NEVER steps entirely. Without this, a job carrying an obsolete
    # `if: false` cleanup skipped ENTIRELY — throwing away every other step's
    # local coverage over a step that neither CI nor the mirror would ever run.
    # That is this mechanism's own failure mode inverted: the gate stops
    # describing what actually ran.
    refused = [
        (step.name or step.uses or f"step-{i}", destructive_commands(step.run))
        for i, step in enumerate(job.steps)
        if step.run
        and classify_condition(step.if_condition) != STEP_NEVER
        and destructive_commands(step.run)
    ]
    if refused:
        # The step label comes from workflow YAML — the untrusted input this
        # whole guard exists to defend against — so it must never reach
        # executable shell unquoted. Interpolated raw into a double-quoted echo,
        # a step named `wipe $(docker compose down -v)` runs that command on the
        # developer's machine while "reporting" the skip, bypassing the safeguard
        # via the exact vector it was written to close. Collapse each label to one
        # bounded line, then shlex.quote the WHOLE diagnostic.
        why = "; ".join(
            f"{_sanitize_label(lbl)} ({', '.join(cmds)})" for lbl, cmds in refused
        )
        message = (
            f"{JOB_SKIP_MARKER}job not mirrored locally — it contains destructive "
            f"step(s): {why}. These are free on an ephemeral runner and would "
            "delete this machine's data, and the rest of the job depends on them "
            "having run. CI runs it in full."
        )
        lines.extend([f"echo {shlex.quote(message)} >&2", "exit 0", ""])
        return "\n".join(lines) + "\n"

    for i, step in enumerate(job.steps):
        label = step.name or step.uses or f"step-{i}"

        # Classified BEFORE the run:/uses: split. A `uses:` step disabled with
        # `if: false` is still disabled — routing it to the `# Skipped step:`
        # branch below would have `dropped_gating_steps()` mark an otherwise
        # clean job INCOMPLETE and exit 5 block `/create-pr`, over coverage CI
        # never ran either.
        mode = classify_condition(step.if_condition)
        if mode == STEP_NEVER:
            # Switched off on purpose. Deliberately NOT the `# Skipped step:`
            # form — the runner counts those as lost coverage. CI does not run
            # this step either, so omitting it locally is faithful, not a gap;
            # flagging it would be a false alarm, which is how a real INCOMPLETE
            # stops being read.
            lines.append(f"# Disabled step: {label} (if: {step.if_condition})")
            continue

        if step.run is None:
            lines.append(f"# Skipped step: {label} (uses: {step.uses}, no local mirror)")
            continue

        if mode is STEP_UNTRANSLATABLE:
            # Deliberately not emitted. Guessing the condition true would run
            # work CI skips (one such step commits and pushes); guessing false
            # silently drops coverage. Naming it keeps the omission visible —
            # the runner reports the job INCOMPLETE off this line.
            lines.append(
                f"# Skipped step: {label} "
                f"(if: {step.if_condition}, condition not evaluable locally)"
            )
            continue

        # Body-level twin of the `if:` problem above. `_rewrite_actions_templates`
        # only maps secrets/env/vars/inputs onto shell variables; `${{ steps.*
        # }}` and `${{ github.* }}` have no local equivalent and pass through
        # verbatim, where bash rejects them ("bad substitution") — so the step
        # cannot run at all. Emitting it anyway makes the job permanently red
        # for a reason the developer cannot fix.
        body = _rewrite_actions_templates(step.run)

        if "${{" in body:
            unresolved = sorted(set(re.findall(r"\$\{\{\s*([^}]+?)\s*\}\}", body)))
            lines.append(
                f"# Skipped step: {label} "
                f"(if: unresolved {', '.join(unresolved)}, "
                f"condition not evaluable locally)"
            )
            continue

        header = f"# Step: {label}"
        if step.if_condition:
            header += f"  [if: {step.if_condition}]"
        lines.append(header)
        if mode == STEP_OVER_RUN:
            # Running unconditionally is deliberate: this gates on whether
            # something changed, so locally it is a superset of CI. Noted
            # because the local run is then stricter than CI, not looser.
            lines.append(
                "#   condition not evaluable locally; running anyway "
                "(CI may skip this step)"
            )

        # Guard BEFORE the subshell, so the subshell body is byte-identical to
        # the unconditional form and stays easy to compare against the workflow.
        if tracks_failure and mode in (STEP_NORMAL, STEP_OVER_RUN):
            lines.append('if [ "$_forge_failed" -eq 0 ]; then')
        elif mode == STEP_ON_FAILURE:
            lines.append('if [ "$_forge_failed" -ne 0 ]; then')

        # A subshell on the LHS of `||` has errexit suppressed *inside its body*
        # too, not just for the outer script — so a multi-command `run:` whose
        # first command fails and last succeeds would exit 0 and report the job
        # green, while the GHA step (`bash -e`) fails at the first command. To
        # keep the status without that suppression: disable errexit around the
        # CALL, re-enable it INSIDE the subshell, then test the captured status.
        # NOT `|| true` anywhere: that swallows the failure and turns a real
        # gate into a no-op, the inverse of the bug this tracking exists for.
        if tracks_failure:
            lines.append("set +e")
        lines.append("(")
        if tracks_failure:
            lines.append("  set -e")
        workdir = step.working_directory or job.working_directory
        if workdir:
            lines.append(f'  cd {shlex.quote(workdir)}')
        for k, v in step.env.items():
            lines.append(_render_env_export(k, str(v), indent="  "))
        for run_line in body.splitlines():
            lines.append(f"  {run_line}")
        lines.append(")")
        if tracks_failure:
            lines.extend([
                "_forge_step_status=$?",
                "set -e",
                '[ "$_forge_step_status" -eq 0 ] || _forge_failed=1',
            ])
        if (tracks_failure and mode in (STEP_NORMAL, STEP_OVER_RUN)) or mode == STEP_ON_FAILURE:
            lines.append("fi")
        lines.append("")

    if tracks_failure:
        lines.extend([
            "# Re-raise the first failure recorded above.",
            'exit "$_forge_failed"',
            "",
        ])
    return "\n".join(lines) + "\n"


def generate_scripts(
    jobs: Iterable[Job],
    out_dir: Path,
    project_root: Path | None = None,
) -> list[Path]:
    """Generate one .sh per job.

    When `project_root` is supplied, the generator looks for a Compose file
    under it and rewrites `localhost:CONTAINER` URLs in each job's env to
    the dev's Compose host ports — fixes the CI-vs-local port mismatch
    (T496) without per-machine `.git/hooks/pre-push` patches. Empty
    `*_PASSWORD` defaults that match a Compose service's password env are
    replaced with `${NAME:-}` env-var refs, never inlined values.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    # env_files: list of project-relative paths the generated script will
    # try to source before any `export`. Discovered here, embedded in
    # render_script. Empty list means no source-block is emitted (zero
    # cost when the project has no .env, no behavior change).
    env_files_rel: list[str] = []

    # password_refs_emitted: tracks whether the Compose introspector
    # substituted any empty `*_PASSWORD` defaults into `${{ env.NAME }}`
    # GHA templates. If yes, the script depends on .env-sourcing being
    # actually wired — otherwise the env-refs resolve empty at run time
    # and the source-block is silently load-bearing-but-broken. Used
    # below to decide whether to warn when no .env was discovered.
    password_refs_emitted = False
    compose_file: Path | None = None

    if project_root is not None:
        from compose_introspector import (
            discover_compose_file,
            discover_env_files,
            load_password_env,
            load_port_map,
            rewrite_env_for_compose,
        )

        compose_file = discover_compose_file(project_root)
        if compose_file is not None:
            port_map = load_port_map(compose_file)
            password_env = load_password_env(compose_file)
            if port_map or password_env:
                # Workflow env can sit at job level (`jobs.<j>.env`) OR step
                # level (`jobs.<j>.steps[].env`). Workflows in the wild often
                # put DATABASE_URL / REDIS_PASSWORD on the test step rather
                # than the job — we have to rewrite both surfaces or the
                # fix only half-lands.
                rewritten_jobs = []
                for j in jobs:
                    j.env = rewrite_env_for_compose(j.env, port_map, password_env)
                    for step in j.steps:
                        if step.env:
                            step.env = rewrite_env_for_compose(
                                step.env, port_map, password_env
                            )
                    rewritten_jobs.append(j)
                jobs = rewritten_jobs
                # Detect whether any password substitution actually fired.
                # The rewrite emits `${{ env.NAME }}` templates that the
                # later `_rewrite_actions_templates` pass turns into bash
                # `${NAME:-}`. If any rewritten env value carries that
                # marker, the source-block is load-bearing.
                password_refs_emitted = any(
                    "${{ env." in str(v)
                    for j in jobs
                    for v in list(j.env.values()) + [
                        sv for step in j.steps for sv in step.env.values()
                    ]
                )

        # T497/T498/T499: discover the dev's .env files so the generated
        # script can source them at run time to resolve the password
        # env-refs the rewrite emitted. compose_file is passed so the
        # discovery can also try ".env" next to the compose file (catches
        # non-canonical compose layouts without needing a pyproject.toml
        # opt-in). Embedded as project-relative paths (POSIX) so the
        # script works from any clone with the same project layout.
        env_paths = discover_env_files(project_root, compose_file=compose_file)
        # T502: a symlinked .env (or absolute pyproject.toml override) may
        # resolve outside project_root — `Path.relative_to` raises ValueError
        # in that case. Fall back to the resolved absolute path; the
        # generated script's `[ -f "$_env_layer" ]` check works either way.
        # Generated scripts are gitignored, so an operator-specific absolute
        # path doesn't damage portability — each operator regenerates locally.
        env_files_rel: list[str] = []
        outside_paths: list[Path] = []
        project_root_resolved = project_root.resolve()
        for ef in env_paths:
            resolved = ef.resolve()
            try:
                env_files_rel.append(
                    resolved.relative_to(project_root_resolved).as_posix()
                )
            except ValueError:
                env_files_rel.append(resolved.as_posix())
                outside_paths.append(resolved)
        if outside_paths:
            joined = ", ".join(str(p) for p in outside_paths)
            print(
                "warning: preflight env file(s) resolve outside project "
                f"root: {joined}. Generated script will source via absolute "
                "path — it still works on this machine, but the path is "
                "operator-machine-specific; other operators must regenerate.",
                file=sys.stderr,
            )

        # T499: when the script relies on .env-sourced password values
        # but no .env was discovered, the generated script will silently
        # fail at run time with empty env-refs. Surface a one-line hint
        # at generation time so the consumer can opt into a non-canonical
        # location via pyproject.toml. Only fires when the source-block
        # is load-bearing — projects without password-rewrites stay
        # quiet.
        if password_refs_emitted and not env_paths:
            print(
                "warning: preflight generated password env-refs from "
                "Compose introspection, but no .env was found at canonical "
                "paths (.env, infrastructure/compose/.env, compose/.env, "
                "or next to the discovered compose file). At run time the "
                "env-refs will resolve empty and DB auth will fail. Opt "
                "into a non-canonical .env location via pyproject.toml:\n"
                "    [tool.forge.preflight]\n"
                '    env_files = ["path/to/your/.env"]',
                file=sys.stderr,
            )

    # Every generated script sources `_local_shims.sh` from its OWN directory
    # and hard-exits when it is absent. Nothing else puts it there, so a fresh
    # out dir produced scripts that all failed with "portability shim missing"
    # and told the reader to run the regenerate that had just produced them.
    # Copied here because this is the only writer into out_dir.
    #
    # Overwritten rather than seeded only-if-missing: the source is the
    # project-local, user-extended copy (install.sh seeds that one and refresh
    # excludes it), while out_dir is generated and gitignored — so copying every
    # time is what makes an edited shim actually reach the scripts.
    shim_src = Path(__file__).parent / "_local_shims.sh"
    if shim_src.exists():
        shutil.copyfile(shim_src, out_dir / "_local_shims.sh")

    written: list[Path] = []
    for job in jobs:
        script_path = out_dir / f"{job.name}.sh"
        script_path.write_text(
            render_script(job, Path(job.file), env_files=env_files_rel or None)
        )
        script_path.chmod(0o755)
        written.append(script_path)
    return written


# --- Drift detection ---------------------------------------------------------

@dataclass
class DriftReport:
    changed: list[str]
    new: list[str]
    removed: list[str]
    # Generated scripts were built against an older GENERATOR_CONTRACT. Kept OUT
    # of has_drift on purpose: workflow drift is the user's doing and should stop
    # the run so they can look, whereas a contract bump is the framework changing
    # under them — that self-heals by regenerating, without a blocking prompt.
    contract_stale: bool = False

    @property
    def has_drift(self) -> bool:
        return bool(self.changed or self.new or self.removed)


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _collect_workflow_hashes(workflows_dir: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not workflows_dir.exists():
        return out
    files = list(workflows_dir.glob("*.yml")) + list(workflows_dir.glob("*.yaml"))
    for f in sorted(files):
        out[f.name] = _hash_file(f)
    return out


def write_lockfile(workflows_dir: Path, lockfile: Path) -> None:
    hashes = _collect_workflow_hashes(workflows_dir)
    lockfile.parent.mkdir(parents=True, exist_ok=True)
    # Trailing newline: drift.lock is committed, so emitting it without one made
    # every `--regenerate` produce a pure "\ No newline at end of file" diff on a
    # tracked file.
    lockfile.write_text(
        json.dumps(
            {"generator_contract": GENERATOR_CONTRACT, "workflow_hashes": hashes},
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def compute_drift(workflows_dir: Path, lockfile: Path) -> DriftReport:
    live = _collect_workflow_hashes(workflows_dir)
    if not lockfile.exists():
        return DriftReport(changed=[], new=sorted(live.keys()), removed=[])
    data = json.loads(lockfile.read_text())
    locked = data.get("workflow_hashes", {})
    changed = sorted(k for k in live if k in locked and live[k] != locked[k])
    new = sorted(k for k in live if k not in locked)
    removed = sorted(k for k in locked if k not in live)
    # Absent key => a lockfile written before contracts were versioned, i.e. the
    # oldest possible contract. Treat as stale rather than assuming current.
    return DriftReport(
        changed=changed,
        new=new,
        removed=removed,
        contract_stale=data.get("generator_contract") != GENERATOR_CONTRACT,
    )


# --- CLI ---------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="script_generator")
    p.add_argument("workflows_dir", type=Path)
    p.add_argument("--out", type=Path, required=True, help="Output dir (e.g. .forge/preflight)")
    p.add_argument("--default-branch", default="main")
    p.add_argument("--protection-mock", type=Path)
    p.add_argument("--check-drift", action="store_true", help="Report drift; do not generate")
    p.add_argument(
        "--project-root",
        type=Path,
        default=None,
        help=(
            "Project root for Compose introspection. Default: parent of "
            "--out's parent (i.e. <root>/.forge/preflight → <root>)."
        ),
    )
    p.add_argument("--json", action="store_true")
    args = p.parse_args(argv)

    lockfile = args.out / "drift.lock"

    if args.check_drift:
        report = compute_drift(args.workflows_dir, lockfile)
        payload = {
            "has_drift": report.has_drift,
            "changed": report.changed,
            "new": report.new,
            "removed": report.removed,
        }
        if args.json:
            print(json.dumps(payload, indent=2))
        else:
            if report.has_drift:
                print("⚠️ Preflight drift detected")
                if report.changed:
                    print(f"  changed: {', '.join(report.changed)}")
                if report.new:
                    print(f"  new: {', '.join(report.new)}")
                if report.removed:
                    print(f"  removed: {', '.join(report.removed)}")
            else:
                print("✓ No drift")
        return 2 if report.has_drift else 0

    # Lazy import — workflow_parser pulls in PyYAML. Keeping it out of the
    # module-top means pure helpers in this file (e.g. _rewrite_actions_templates)
    # are testable on any Python without PyYAML installed.
    from workflow_parser import derive_gating_jobs, load_protection_required

    required = None
    if args.protection_mock and args.protection_mock.exists():
        required = load_protection_required(args.protection_mock)
    jobs = derive_gating_jobs(args.workflows_dir, args.default_branch, required)
    # Compose introspection (T496): the dev's running Compose stack is the
    # ground truth for service host ports. Resolve the project root from
    # `--out` (`<project_root>/.forge/preflight`) so the generator can find
    # `docker-compose.yml` and rewrite container-port literals from the
    # workflow into the dev's actual host-port mappings.
    project_root = args.project_root or args.out.resolve().parent.parent
    written = generate_scripts(jobs, args.out, project_root=project_root)
    write_lockfile(args.workflows_dir, lockfile)

    if args.json:
        print(json.dumps([str(p) for p in written], indent=2))
    else:
        for p in written:
            print(f"wrote {p}")
        print(f"wrote {lockfile}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
